Using TensorFlow backend.
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 81, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 75, in _path_stat
FileNotFoundError: [Errno 2] No such file or directory: '/home/piyushsanghi_uchicago_edu/.local/lib/python3.5/site-packages/requests/__init__.cpython-35m-x86_64-linux-gnu.so'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "CNN_Trump.py", line 1, in <module>
    from keras import applications
  File "/home/piyushsanghi_uchicago_edu/.local/lib/python3.5/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/piyushsanghi_uchicago_edu/.local/lib/python3.5/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/home/piyushsanghi_uchicago_edu/.local/lib/python3.5/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/home/piyushsanghi_uchicago_edu/.local/lib/python3.5/site-packages/keras/backend/__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/home/piyushsanghi_uchicago_edu/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/home/piyushsanghi_uchicago_edu/.local/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/piyushsanghi_uchicago_edu/.local/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 88, in <module>
    from tensorflow.python import keras
  File "/home/piyushsanghi_uchicago_edu/.local/lib/python3.5/site-packages/tensorflow/python/keras/__init__.py", line 24, in <module>
    from tensorflow.python.keras import activations
  File "/home/piyushsanghi_uchicago_edu/.local/lib/python3.5/site-packages/tensorflow/python/keras/activations.py", line 24, in <module>
    from tensorflow.python.keras.utils.generic_utils import deserialize_keras_object
  File "/home/piyushsanghi_uchicago_edu/.local/lib/python3.5/site-packages/tensorflow/python/keras/utils/__init__.py", line 35, in <module>
    from tensorflow.python.keras.utils.multi_gpu_utils import multi_gpu_model
  File "/home/piyushsanghi_uchicago_edu/.local/lib/python3.5/site-packages/tensorflow/python/keras/utils/multi_gpu_utils.py", line 22, in <module>
    from tensorflow.python.keras.engine.training import Model
  File "/home/piyushsanghi_uchicago_edu/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/training.py", line 37, in <module>
    from tensorflow.python.keras.engine import distributed_training_utils
  File "/home/piyushsanghi_uchicago_edu/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/distributed_training_utils.py", line 25, in <module>
    from tensorflow.python.keras import callbacks
  File "/home/piyushsanghi_uchicago_edu/.local/lib/python3.5/site-packages/tensorflow/python/keras/callbacks.py", line 53, in <module>
    import requests
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1113, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1240, in find_spec
  File "<frozen importlib._bootstrap_external>", line 89, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 81, in _path_is_mode_type
KeyboardInterrupt
